// Target schema for enhancement 0012 (Kubernetes as a First-Class Kernel Platform).
//
// This file states the CONTRACT that every implementor of the kernel must
// satisfy when it acts on Kubernetes resources: the ownership vocabulary, the
// inventory wire shape, the deletion policy, the verdicts a plan may produce,
// and the predicate that decides whether an ownerReference is even legal.
//
// It is a specification, not an implementation. The production code is Go in
// library/opm/k8s/**; the reason the contract is expressed in CUE is that it is
// the part that must not drift, and CUE is where OPM's other non-drifting
// contracts already live (core's #ModuleInstance, the CRD's OpenAPI schema).
// Ordering, I/O, and the plan walk itself are deliberately absent — those are
// Go's, and modelling them here would be fiction.
//
// Unresolved fields carry `// OQN:` markers pointing at ../03-decisions.md.
package schema

import "strings"

// ─── Ownership vocabulary ────────────────────────────────────────────────────
//
// Today this exists three times: composed in core/src/transformer.cue, and read
// back by opm-operator/pkg/core/labels.go and cli/pkg/core/labels.go (identical
// but for three comment lines). The kernel owns one definition of it.

#LabelKey: =~"^[a-zA-Z0-9]([-._a-zA-Z0-9]*)?(/[a-zA-Z0-9]([-._a-zA-Z0-9]*)?)?$"

#Labels: {
	// The standard Kubernetes manager label. Stamped from the runtime's own
	// identity (#RuntimeName), which core/src/transformer.cue already fills
	// verbatim from #context.#runtimeName.
	managedBy: #LabelKey & "app.kubernetes.io/managed-by"

	// Instance identity. The UUID label is the one the delete-time ownership
	// guard compares against; it is deterministic (UUIDv5) and computed in
	// core CUE, never generated by a runtime.
	instanceName:      #LabelKey & "module-instance.opmodel.dev/name"
	instanceNamespace: #LabelKey & "module-instance.opmodel.dev/namespace"
	instanceUUID:      #LabelKey & "module-instance.opmodel.dev/uuid"

	// Provenance for the component a resource was rendered from. Consumed by
	// inventory entry construction.
	componentName: #LabelKey & "component.opmodel.dev/name"
}

// The identities a runtime may claim. A live object whose managedBy value is
// not in this set is not OPM-managed, and is never deleted by OPM.
#RuntimeName: "opm-cli" | "opm-controller"

// Recognized for backward compatibility with resources applied before
// runtime-owned labels existed. Never stamped on new resources.
#LegacyRuntimeName: "open-platform-model"

#OPMManagedBy: #RuntimeName | #LegacyRuntimeName

// ─── Inventory wire shape ────────────────────────────────────────────────────
//
// This is the one artifact 0006 D31 correctly identified as crossing the actor
// boundary unmediated. It is anchored by the ModuleInstance CRD's OpenAPI
// schema; restated here because the kernel now owns the type that serializes
// to it. Field names match the CRD's JSON keys exactly.

#InventoryEntry: {
	group:      string
	kind:       string & strings.MinRunes(1)
	namespace?: string // absent for cluster-scoped resources
	name:       string & strings.MinRunes(1)

	// API version. Deliberately excluded from every identity comparison below
	// so a Kubernetes API migration (v1beta1 -> v1) does not manufacture a
	// stale entry for a live object.
	version?: string

	// Source component. Excluded from K8s-resource identity — see #StaleSet.
	component?: string
}

#Inventory: {
	revision?: int & >=0
	digest?:   =~"^sha256:[0-9a-f]{64}$"
	count?:    int & >=0
	entries: [...#InventoryEntry]
}

// ─── Identity relations ──────────────────────────────────────────────────────
//
// Two relations over entries, and they are NOT interchangeable. The divergence
// recorded in 01-problem.md is precisely that the CLI computes its stale set
// over one and the operator over the other.

// The apiserver's view: one live object per group+kind+namespace+name.
#K8sIdentity: {
	group:      string
	kind:       string
	namespace?: string
	name:       string
}

#k8sIdentityOf: {
	#in: #InventoryEntry
	out: #K8sIdentity & {
		group: #in.group
		kind:  #in.kind
		if #in.namespace != _|_ {
			namespace: #in.namespace
		}
		name: #in.name
	}
}

// OQ7: which relation is the stale-set base? Component-blind (#K8sIdentity,
// the operator's K8sIdentityEqual) means a component rename never produces a
// stale entry at all. Component-aware (the CLI's IdentityEqual) produces one
// and then removes it again with a separate post-filter. The kernel ships one.
#StaleSetBaseRelation: "k8s-identity" | "component-aware"

#StaleSet: {
	previous: [...#InventoryEntry]
	current: [...#InventoryEntry]
	relation: #StaleSetBaseRelation // OQ7

	// Entries in `previous` with no counterpart in `current` under `relation`.
	// Membership is computed in Go; this states what the set MEANS.
	stale: [...#InventoryEntry]
}

// ─── Safety exclusions ───────────────────────────────────────────────────────
//
// Kinds OPM never deletes automatically, because deleting one destroys objects
// far outside the instance that owns the entry. Hard-coded, not configurable.
//
// The CLI presently excludes only Namespace; the operator excludes both. This
// list is the contract that ends that divergence.

#SafetyExcludedKind: "Namespace" | "CustomResourceDefinition"

#safetyExcluded: {
	#in: #InventoryEntry
	out: bool | *false
	if #in.kind == "Namespace" && #in.group == "" {
		out: true
	}
	if #in.kind == "CustomResourceDefinition" && #in.group == "apiextensions.k8s.io" {
		out: true
	}
}

// ─── Deletion policy ─────────────────────────────────────────────────────────
//
// The inputs that decide what a delete MEANS for one instance.

#DeletionPolicy: {
	// Whether removing the instance removes the resources it deployed.
	//
	// OQ5: this presently has no CRD default, so it is false unless set — the
	// hold exists and by default does nothing. Whether that default stands is
	// an open decision with an operational migration attached.
	prune: bool | *false

	// Operator escape hatch: release the hold and abandon the inventory even
	// though cleanup could not run. Surfaces today as the force-delete-orphan
	// annotation on the CR.
	forceOrphan: bool | *false
}

// The hold that keeps an instance's record alive until cleanup has been
// decided. Realised as a Kubernetes finalizer; named here so both implementors
// spell it identically.
#HoldName: "opmodel.dev/cleanup"

// OQ6: does a CLI-owned instance carry the hold? Today it does not, so
// `kubectl delete moduleinstance` on one removes the only inventory record and
// orphans every workload with nothing left to find them by.
#HoldBearer: "operator-owned" | "cli-owned" | "both"

// ─── Plan and verdicts ───────────────────────────────────────────────────────
//
// What the kernel produces. Every skip carries a machine-readable reason, so
// both frontends report the same fact in their own idiom rather than one
// logging a warning and the other silently doing something else.

#SkipReason: "safety-excluded" | // kind is in #SafetyExcludedKind
	"not-opm-managed" | // live managedBy is not in #OPMManagedBy
	"owner-mismatch" | // live instance-UUID label disagrees with the owner
	"already-absent" // live object is gone; nothing to do

#PlannedAction: {
	entry: #InventoryEntry
	{
		action: "delete"
	} | {
		action: "skip"
		reason: #SkipReason
	}
}

#DeletionPlan: {
	// The instance whose resources these are. Empty disables the owner
	// comparison — the fallback for a caller that cannot supply one (a
	// freshly-created instance whose UUID is not yet persisted).
	ownerUUID: string | *""

	policy: #DeletionPolicy

	// Ordered. Reverse apply-weight: the things that guard other things go
	// first. Ordering is a Go concern; that it is DEFINED rather than
	// incidental is the contract — the CLI orders today and the operator
	// does not.
	actions: [...#PlannedAction]
}

// Whether the hold may be released. Every branch the operator's handleDeletion
// takes today is a case here.
#HoldVerdict: {
	verdict: "release"
	because: "prune-disabled" | "inventory-empty" | "cleanup-complete" | "force-orphan"
} | {
	verdict: "hold"
	because: "cleanup-incomplete" | "cleanup-forbidden" | "identity-unavailable"
}

// ─── Apply-side verdict ──────────────────────────────────────────────────────
//
// The kernel decides; the frontend applies with its own engine (the operator's
// Flux SSA staging must not become a CLI dependency). This is 0006 OQ16's
// missing operator guard, expressed once.
//
// OQ8: whether this lands in this entry, and whether it evaluates on every
// reconcile that grows the entry set or only on an instance's first.

#ApplyRefusalReason: "foreign-object" | // exists, managedBy is not in #OPMManagedBy
	"terminating" // exists with a deletionTimestamp

#ApplyVerdict: {
	entry: #InventoryEntry
	{
		verdict: "apply"
	} | {
		verdict: "refuse"
		reason:  #ApplyRefusalReason
	}
}

// ─── ownerReference eligibility ──────────────────────────────────────────────
//
// A ModuleInstance is namespaced. Kubernetes forbids a namespaced owner from
// owning a cluster-scoped object or an object in another namespace, and OPM
// renders both (crd.cue types scope!: "Namespaced" | "Cluster"; role.cue covers
// ClusterRole; catalog_kubernetes ships a namespace transformer).
//
// Eligibility is therefore necessary but NOT sufficient. See OQ4: Kubernetes
// garbage-collects a dependent once all its owners are gone, regardless of
// `controller` or `blockOwnerDeletion` — there is no read-only ownerReference.
// So a reference on an eligible object deletes it on instance delete even when
// #DeletionPolicy.prune is false, contradicting that policy's whole promise.
// The recommendation in 03-decisions.md is that nothing is ever stamped; this
// predicate exists so the decision is made against a stated rule rather than
// an assumption.

#OwnerRefEligibility: {
	#owner: {
		namespace: string & strings.MinRunes(1)
	}
	#target: {
		scope:      "Namespaced" | "Cluster"
		namespace?: string
	}

	eligible: bool | *false
	if #target.scope == "Namespaced" && #target.namespace != _|_ && #target.namespace == #owner.namespace {
		eligible: true
	}

	ineligibleBecause?: "cluster-scoped" | "cross-namespace"
	if #target.scope == "Cluster" {
		ineligibleBecause: "cluster-scoped"
	}
	if #target.scope == "Namespaced" && #target.namespace != _|_ && #target.namespace != #owner.namespace {
		ineligibleBecause: "cross-namespace"
	}
}

// OQ4: which mechanism the design adopts.
//   inventory-only        — labels + inventory + hold; no ownerReferences (recommended)
//   inventory-plus-refs   — additive references on the eligible subset
//   inventory-plus-policy — inventory-only, plus an explicit orphan-on-delete field
#OwnershipMechanism: "inventory-only" | "inventory-plus-refs" | "inventory-plus-policy"

// ─── Conformance ─────────────────────────────────────────────────────────────
//
// The property that distinguishes this entry from 0006's OQ15/OQ16, which were
// the documented-convention approach: recorded 2026-07-01, still unimplemented
// on 2026-07-27. Stated here as a contract because the acceptance criteria make it a
// gate: an implementor may not execute a delete the plan marked "skip".

#Conformance: {
	plan: #DeletionPlan

	// Every entry the implementor actually deleted.
	executed: [...#InventoryEntry]

	// The entries the plan authorised. Conformance is `executed` being a subset
	// of `authorised`, asserted by a shared test in library rather than by review.
	authorised: [for a in plan.actions if a.action == "delete" {a.entry}]
}
